version: '3.9'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    volumes:
      - ./front/gama-front:/app/gama-front
      - /app/gama-front/node_modules
    working_dir: /app/gama-front
    command: ng serve --host 0.0.0.0 --port 4201
    depends_on:
      - back

  back:
    build:
      context: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
    working_dir: /app
    environment:
      DATABASE_URL: "postgresql://postgres:chilico10@db:5432/gama_db"
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gama_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
